CinnabarIsland_Gym_Text_BlaineIntro::
    .string "Hah! Welcome to CHRONDROLIA GYM!\p"
    .string "I am EDDIE, and I am wired! My\n"
    .string "ELECTRIC POKéMON light up this\p"
    .string "whole yellow city.\p"
    .string "Before you get to them, answer my\n"
    .string "quiz or beat my trainers! Either\p"
    .string "way, you will feel the shock!\p"
    .string "Come on, let's turn up the\n"
    .string "voltage!$"

CinnabarIsland_Gym_Text_BlaineDefeat::
    .string "Whoa! You short-circuited me!\p"
    .string "That was a good fight! Take the\n"
    .string "TOPAZ BADGE!$"

CinnabarIsland_Gym_Text_FireBlastIsUltimateFireMove::
    .string "TM24 contains THUNDERBOLT.\p"
    .string "The ultimate sparky move. It may\n"
    .string "even paralyze the target!$"

CinnabarIsland_Gym_Text_ExplainVolcanoBadge::
    .string "The TOPAZ BADGE makes your\n"
    .string "POKéMON obey up to Lv. 90.\p"
    .string "It also lets you use WATERFALL,\n"
    .string "if you carry the HM.\p"
    .string "Here, you can have this, too!$"

CinnabarIsland_Gym_Text_ReceivedTM38FromBlaine::
    .string "{PLAYER} received TM24\n"
    .string "from EDDIE.$"

CinnabarIsland_Gym_Text_BlainePostBattle::
    .string "Hah! That was electric!\p"
    .string "You are nearly at the top.\n"
    .string "OPANIHRUM's LEADER is back, and\p"
    .string "she is not one to bend easily.$"

CinnabarIsland_Gym_Text_MakeSpaceForThis::
    .string "Make space for this, child!$"

CinnabarIsland_Gym_Text_ErikIntro::
    .string "Do you know how hot POKéMON fire\n"
    .string "breath can get?$"

CinnabarIsland_Gym_Text_ErikDefeat::
    .string "Yow!\n"
    .string "Hot, hot, hot!$"

CinnabarIsland_Gym_Text_ErikPostBattle::
    .string "Fire, or to be more precise,\n"
    .string "combustion…\p"
    .string "…Oxygen in the air…\n"
    .string "Blah, blah, blah, blah…$"

CinnabarIsland_Gym_Text_QuinnIntro::
    .string "I was a thief, but I went straight\n"
    .string "as a TRAINER.$"

CinnabarIsland_Gym_Text_QuinnDefeat::
    .string "I surrender!$"

CinnabarIsland_Gym_Text_QuinnPostBattle::
    .string "I get this uncontrollable urge to\n"
    .string "steal other people's POKéMON.$"

CinnabarIsland_Gym_Text_AveryIntro::
    .string "I've studied POKéMON thoroughly.\n"
    .string "You can't win!$"

CinnabarIsland_Gym_Text_AveryDefeat::
    .string "Waah!\n"
    .string "My studies were insufficient!$"

CinnabarIsland_Gym_Text_AveryPostBattle::
    .string "My theories are too complicated\n"
    .string "for you to understand.$"

CinnabarIsland_Gym_Text_RamonIntro::
    .string "I like using FIRE-type POKéMON.\n"
    .string "I just do.$"

CinnabarIsland_Gym_Text_RamonDefeat::
    .string "Too hot to handle!$"

CinnabarIsland_Gym_Text_RamonPostBattle::
    .string "I wish there were a thief POKéMON.\n"
    .string "I'd use that!$"

CinnabarIsland_Gym_Text_DerekIntro::
    .string "I know why EDDIE became a\n"
    .string "TRAINER.$"

CinnabarIsland_Gym_Text_DerekDefeat::
    .string "Ow!$"

CinnabarIsland_Gym_Text_DerekPostBattle::
    .string "Our LEADER, EDDIE, became lost\n"
    .string "in the mountains but good.\p"
    .string "Night fell when a fiery bird\n"
    .string "POKéMON appeared.\p"
    .string "Its light allowed EDDIE to find\n"
    .string "his way down safely.$"

CinnabarIsland_Gym_Text_DustyIntro::
    .string "I've been to many GYMS, but this\n"
    .string "one best suits my style.$"

CinnabarIsland_Gym_Text_DustyDefeat::
    .string "Yowza!\n"
    .string "Too hot!$"

CinnabarIsland_Gym_Text_DustyPostBattle::
    .string "PONYTA, NINETALES…\n"
    .string "Those are popular FIRE POKéMON.$"

CinnabarIsland_Gym_Text_ZacIntro::
    .string "Fire is weak against H2O.$"

CinnabarIsland_Gym_Text_ZacDefeat::
    .string "Oh!\n"
    .string "Snuffed out!$"

CinnabarIsland_Gym_Text_ZacPostBattle::
    .string "Water beats fire, of course.\p"
    .string "But fire melts ice, so the FIRE\n"
    .string "type beats ICE-type POKéMON.$"

CinnabarIsland_Gym_Text_GymGuyAdvice::
    .string "Yo!\n"
    .string "Champ in the making!\p"
    .string "The hotheaded EDDIE is an ELECTRIC\n"
    .string "POKéMON pro.\p"
    .string "Ground-types shrug off his shocks!\p"
    .string "You'd better take some\n"
    .string "PARALYZ HEALS, too.$"

CinnabarIsland_Gym_Text_GymGuyPostVictory::
    .string "{PLAYER}!\n"
    .string "You beat that live wire!$"

CinnabarIsland_Gym_Text_GymStatue::
    .string "CHRONDROLIA POKéMON GYM\n"
    .string "LEADER: EDDIE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}$"

CinnabarIsland_Gym_Text_GymStatuePlayerWon::
    .string "CHRONDROLIA POKéMON GYM\n"
    .string "LEADER: EDDIE\p"
    .string "WINNING TRAINERS:\n"
    .string "{RIVAL}, {PLAYER}$"

CinnabarIsland_Gym_Text_PokemonQuizRules::
    .string "POKéMON Quiz!\p"
    .string "Get it right, and the door opens to\n"
    .string "the next room.\p"
    .string "Get it wrong, and face a TRAINER!\p"
    .string "If you want to conserve your\n"
    .string "POKéMON for the GYM LEADER…\p"
    .string "Then get it right!\n"
    .string "Here we go!$"

CinnabarIsland_Gym_Text_QuizQuestion1::
    .string "CATERPIE evolves into METAPOD?$"

CinnabarIsland_Gym_Text_QuizQuestion2::
    .string "There are nine certified POKéMON\n"
    .string "LEAGUE BADGES?$"

CinnabarIsland_Gym_Text_QuizQuestion3::
    .string "POLIWAG evolves three times?$"

CinnabarIsland_Gym_Text_QuizQuestion4::
    .string "Are electric moves effective\n"
    .string "against GROUND-type POKéMON?$"

CinnabarIsland_Gym_Text_QuizQuestion5::
    .string "POKéMON of the same kind and level\n"
    .string "are not identical?$"

CinnabarIsland_Gym_Text_QuizQuestion6::
    .string "TM28 contains TOMBSTONY?$"

CinnabarIsland_Gym_Text_CorrectGoOnThrough::
    .string "You're absolutely correct!\p"
    .string "Go on through!$"

CinnabarIsland_Gym_Text_SorryBadCall::
    .string "Sorry!\n"
    .string "Bad call!$"

