Route1_Text_WorkAtPokeMartTakeSample::
    .string "Hi!\n"
    .string "I work at a POKéMON MART.\p"
    .string "It's part of a convenient chain\n"
    .string "selling all sorts of items.\p"
    .string "Please, visit us in OPANIHRUM.\p"
    .string "I know, I'll give you a sample.\n"
    .string "Here you go!$"

Route1_Text_ComeSeeUsIfYouNeedPokeBalls::
    .string "Please come see us if you need\n"
    .string "POKé BALLS for catching POKéMON.$"

Route1_Text_PutPotionAway::
    .string "{PLAYER} put the POTION away in\n"
    .string "the BAG's ITEMS POCKET.$"

Route1_Text_CanJumpFromLedges::
    .string "Notice how the grass changes color\n"
    .string "as you walk this road?\p"
    .string "Red near GRENALUX, black and teal\n"
    .string "near OPANIHRUM.\p"
    .string "Grown-ups say the crystals do it.$"

Route1_Text_RouteSign::
    .string "ROUTE 1\n"
    .string "GRENALUX - OPANIHRUM$"

