PalletTown_Museum_MapScripts::
	.byte 0

PalletTown_Museum_EventScript_Curator::
	msgbox PalletTown_Museum_Text_Curator, MSGBOX_NPC
	end

PalletTown_Museum_EventScript_OldMan::
	msgbox PalletTown_Museum_Text_OldMan, MSGBOX_NPC
	end

PalletTown_Museum_EventScript_GarnetCase::
	msgbox PalletTown_Museum_Text_GarnetCase, MSGBOX_SIGN
	end

PalletTown_Museum_EventScript_AuraCase::
	msgbox PalletTown_Museum_Text_AuraCase, MSGBOX_SIGN
	end
